[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2021"



[dependencies]
rustls = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
rand = "0.8"
secp256k1 = "0.18"
web3 = "0.18"


[lib]
crate-type = ["cdylib"]
